services:
  - type: background
    name: twitch-to-restream-auto
    env: docker
    autoDeploy: false
    envVars:
      - key: TWITCH_USER
        value: fahrenalfred
      - key: RESTREAM_KEY
        value: 
