services:
  - type: background
    name: twitch-to-restream-auto
    env: docker
    autoDeploy: false
    envVars:
      - key: TWITCH_USER
        value: TU_NOMBRE_DE_CANAL_TWITCH
      - key: RESTREAM_KEY
        value: TU_STREAM_KEY_RESTREAM
